//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyGames
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int IDe { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public int IDRole { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
