//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyGames
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableGames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableGames()
        {
            this.Orders = new HashSet<Orders>();
            this.Storage = new HashSet<Storage>();
        }
    
        public int IDGame { get; set; }
        public string Name { get; set; }
        public int Kolvo_players_min { get; set; }
        public int Kolvo_players_max { get; set; }
        public int Age_players { get; set; }
        public int Producer { get; set; }
        public Nullable<int> Genre { get; set; }
        public int Cost { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Producers Producers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storage> Storage { get; set; }
    }
}
